# Copyright (C) 2023 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Publish Sphinx Documentation

on:
  push:
    branches:
      - "**"

jobs:
  publish_sphinx_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get install libcdd-dev libgmp-dev python3-dev
          python3 -m pip install --upgrade pip

      - name: Install pycvxset with docs and testing dependencies
        run: |
          pip install --editable ".[with_docs_and_tests]"

      - name: Build the docs from sphinx
        run: |
          cd docs
          sphinx-build -b html source build
          make html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
